const ACCOUNT_ORIGIN='https://accounts.ignifire.app';
const DOWNLOAD_MANIFEST_URL='https://raw.githubusercontent.com/FennXWeb/firefly-music-player/beta/updates/latest.json';
let downloadUrl='https://github.com/FennXWeb/firefly-music-player/releases/download/beta-v0.1.49/Ignifire-0.1.49-Setup.exe';
const state={user:null,library:null,cloud:{revision:0,syncedAt:null,storageUsed:0},view:'home',query:'',queue:[],queueOriginal:[],index:-1,shuffle:false,repeat:'off'};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const audio=$('#audio');

function esc(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function initials(name='Ignifire listener'){const words=String(name).trim().split(/\s+/).filter(Boolean);return(words.length>1?words[0][0]+words.at(-1)[0]:words[0]?.[0]||'I').toUpperCase()}
function formatTime(seconds=0){const value=Math.max(0,Math.floor(Number(seconds)||0));return`${Math.floor(value/60)}:${String(value%60).padStart(2,'0')}`}
function setRange(input,value){const next=Math.max(0,Math.min(100,Number(value)||0));input.value=next;input.style.setProperty('--range',`${next}%`)}
function toast(title,detail=''){const item=document.createElement('div');item.className='toast';item.innerHTML=`<b>${esc(title)}</b>${detail?`<span>${esc(detail)}</span>`:''}`;$('#toasts').append(item);setTimeout(()=>item.remove(),3200)}
function validInstallerUrl(value=''){try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='github.com'&&url.pathname.startsWith('/FennXWeb/firefly-music-player/releases/download/')&&/Ignifire-[^/]+-Setup\.exe$/i.test(url.pathname)}catch{return false}}
function applyDownloadUrl(value){if(!validInstallerUrl(value))return;downloadUrl=value;$$('[data-desktop-download]').forEach(link=>{link.href=value;link.removeAttribute('target');link.removeAttribute('rel')})}
async function resolveDownloadUrl(){try{const response=await fetch(DOWNLOAD_MANIFEST_URL,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)return;const manifest=await response.json();applyDownloadUrl(manifest.downloadUrl)}catch{/* The known-good published installer remains available. */}}
function allAlbums(){return state.library?.albums||[]}
function allTracks(){return allAlbums().flatMap(album=>(album.tracks||[]).map(track=>({...track,cover:album.customCover||'',coverClass:album.cover||'',albumYear:album.year,genre:album.genre}))) }
function playableTracks(tracks=allTracks()){return tracks.filter(track=>track.playable&&track.cloudHash)}
function albumById(id){return allAlbums().find(album=>album.id===id)}
function trackById(id){return allTracks().find(track=>track.id===id)}
function streamURL(track){return`${ACCOUNT_ORIGIN}/v1/web/stream/${encodeURIComponent(track.cloudHash)}`}
function coverStyle(item){const image=item?.customCover||item?.cover||'';return image?`style="background-image:url('${esc(image)}')"`:''}
function albumCover(album,extra=''){return`<div class="cover ${album.customCover?'':'cover-fallback'} ${extra}" ${coverStyle(album)}></div>`}
function pageHeading(eyebrow,title,description){return`<header class="page-heading"><div><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></div></header>`}

function albumCard(album){return`<article class="album-card" data-album="${esc(album.id)}">${albumCover(album)}<button class="card-play" data-play-album="${esc(album.id)}" aria-label="Play ${esc(album.title)}">▶</button><h3>${esc(album.title)}</h3><p>${esc(album.artist)}${album.year?` · ${album.year}`:''}</p></article>`}
function trackRows(tracks){return`<table class="track-table"><thead><tr><th>#</th><th>TRACK</th><th>ALBUM</th><th>PLAYS</th><th></th></tr></thead><tbody>${tracks.map((track,index)=>`<tr data-track="${esc(track.id)}" class="${state.queue[state.index]?.id===track.id?'current':''}"><td class="track-number">${index+1}</td><td><div class="track-main"><div class="track-thumb ${track.cover?'':'cover-fallback'}" ${coverStyle(track)}></div><div class="track-copy"><b>${esc(track.title)}</b><span>${esc(track.artist)}</span></div></div></td><td>${esc(track.album)}</td><td>${track.plays||0}</td><td><button class="track-action" data-play-track="${esc(track.id)}" aria-label="Play ${esc(track.title)}">${track.playable?'▶':'—'}</button></td></tr>`).join('')}</tbody></table>`}
function playlistTracks(playlist){if(Array.isArray(playlist.children)&&playlist.children.length)return[...new Map(playlist.children.flatMap(playlistTracks).map(track=>[track.id,track])).values()];return(playlist.trackIds||[]).map(trackById).filter(Boolean)}
function playlistCard(playlist){const design=playlist.coverDesign||{},a=/^#[0-9a-f]{3,8}$/i.test(design.colorA||'')?design.colorA:(playlist.color||'#7d4cff'),b=/^#[0-9a-f]{3,8}$/i.test(design.colorB||'')?design.colorB:'#ff765f',image=design.image?`background-image:linear-gradient(#16111b33,#16111b66),url('${esc(design.image)}');background-size:cover;background-position:center;`:'';return`<article class="playlist-card" data-playlist="${esc(playlist.id)}"><div class="playlist-cover" style="--a:${esc(a)};--b:${esc(b)};${image}"><span>${playlist.children?.length?'MASTER PLAYLIST':'PLAYLIST'}</span><b>${esc(design.title||playlist.title)}</b></div><button class="card-play" data-play-playlist="${esc(playlist.id)}" aria-label="Play ${esc(playlist.title)}">▶</button><h3>${esc(playlist.title)}</h3><p>${playlistTracks(playlist).length} tracks</p></article>`}

function renderHome(){const tracks=allTracks(),playable=playableTracks(tracks),recent=[...tracks].filter(track=>track.lastPlayed).sort((a,b)=>b.lastPlayed-a.lastPlayed).slice(0,6),albums=[...allAlbums()].sort((a,b)=>Math.max(...b.tracks.map(track=>track.added||0))-Math.max(...a.tracks.map(track=>track.added||0))).slice(0,6);return`<section class="hero"><div class="hero-copy"><span class="eyebrow">YOUR CLOUD LIBRARY</span><h1>Every song.<br>Right where you left it.</h1><p>Stream the music you synced from Ignifire for Windows. The web edition stays focused on listening while your full library tools remain in the desktop app.</p><div class="hero-actions"><button class="hero-play" data-play-all>▶ Play library</button><button class="hero-shuffle" data-shuffle-all>⌘ Shuffle all</button></div></div><div class="hero-orbit"><div class="hero-disc"></div></div></section>${recent.length?`<section class="section"><div class="section-head"><div><span class="eyebrow">BACK IN ROTATION</span><h2>Recently played</h2></div><button data-view="songs">View songs</button></div>${trackRows(recent)}</section>`:''}${albums.length?`<section class="section"><div class="section-head"><div><span class="eyebrow">FRESHLY SYNCED</span><h2>Recently added</h2></div><button data-view="albums">View albums</button></div><div class="card-row">${albums.map(albumCard).join('')}</div></section>`:''}${!playable.length?cloudLibraryNotice():''}`}
function renderAlbums(){const query=state.query.toLowerCase(),albums=allAlbums().filter(album=>`${album.title} ${album.artist} ${album.genre}`.toLowerCase().includes(query));return`${pageHeading('LIBRARY','Albums',`${albums.length} synced release${albums.length===1?'':'s'}`)}<div class="album-grid">${albums.map(albumCard).join('')}</div>${albums.length?'':noResults()}`}
function renderAlbum(id){const album=albumById(id);if(!album)return renderAlbums();const tracks=(album.tracks||[]).map(track=>({...track,cover:album.customCover||'',coverClass:album.cover||''}));return`<button class="secondary-action" data-view="albums" style="border:1px solid var(--line);border-radius:11px;padding:9px 14px;cursor:pointer">← All albums</button><section class="section" style="margin-top:24px"><div style="display:grid;grid-template-columns:minmax(180px,260px) 1fr;gap:30px;align-items:end">${albumCover(album)}<div><span class="eyebrow">ALBUM</span><h1 style="font-size:clamp(38px,6vw,70px);letter-spacing:-.06em;margin:10px 0">${esc(album.title)}</h1><p style="color:var(--muted)">${esc(album.artist)}${album.year?` · ${album.year}`:''} · ${tracks.length} tracks</p><div class="hero-actions"><button class="hero-play" data-play-album="${esc(album.id)}">▶ Play</button><button class="hero-shuffle" data-shuffle-album="${esc(album.id)}">⌘ Shuffle</button></div></div></div></section><section class="section">${trackRows(tracks)}</section>`}
function renderSongs(){const query=state.query.toLowerCase(),tracks=allTracks().filter(track=>`${track.title} ${track.artist} ${track.album}`.toLowerCase().includes(query)).sort((a,b)=>a.title.localeCompare(b.title));return`${pageHeading('LIBRARY','Songs',`${tracks.length} synced track${tracks.length===1?'':'s'}`)}${tracks.length?trackRows(tracks):noResults()}`}
function renderPlaylists(){const playlists=state.library?.playlists||[],query=state.query.toLowerCase(),visible=playlists.filter(playlist=>playlist.title.toLowerCase().includes(query));return`${pageHeading('COLLECTIONS','Playlists',`${visible.length} playlist${visible.length===1?'':'s'} from your desktop library`)}<div class="playlist-grid">${visible.map(playlistCard).join('')}</div>${visible.length?'':noResults()}`}
function findPlaylist(id,list=state.library?.playlists||[]){for(const playlist of list){if(playlist.id===id)return playlist;const nested=findPlaylist(id,playlist.children||[]);if(nested)return nested}return null}
function renderPlaylist(id){const playlist=findPlaylist(id);if(!playlist)return renderPlaylists();const tracks=playlistTracks(playlist);return`<button class="secondary-action" data-view="playlists" style="border:1px solid var(--line);border-radius:11px;padding:9px 14px;cursor:pointer">← All playlists</button>${pageHeading(playlist.children?.length?'MASTER PLAYLIST':'PLAYLIST',playlist.title,`${tracks.length} track${tracks.length===1?'':'s'}`)}<div class="hero-actions" style="margin-bottom:25px"><button class="hero-play" data-play-playlist="${esc(playlist.id)}">▶ Play</button><button class="hero-shuffle" data-shuffle-playlist="${esc(playlist.id)}">⌘ Shuffle</button></div>${tracks.length?trackRows(tracks):noResults()}`}
function noResults(){return`<div class="empty-state"><h2>Nothing found</h2><p>Try a different title, artist, album, or playlist name.</p></div>`}
function cloudLibraryNotice(){const tracks=allTracks(),hasSnapshot=state.cloud.revision>0||Boolean(state.cloud.syncedAt),hasStoredData=state.cloud.storageUsed>0;if(tracks.length)return`<div class="empty-state"><img src="https://accounts.ignifire.app/ignifire-logo.png" alt=""><h2>Your library is here, but its audio is not</h2><p>${tracks.length} track${tracks.length===1?' is':'s are'} in the cloud snapshot, but no streamable audio files were attached. Update Ignifire for Windows and run Sync now again; the desktop app will now report the exact file if an upload fails.</p><a class="primary-action" data-desktop-download href="${downloadUrl}" style="padding:15px 20px;border-radius:14px;text-decoration:none">Download Ignifire</a></div>`;if(hasSnapshot||hasStoredData)return`<div class="empty-state"><img src="https://accounts.ignifire.app/ignifire-logo.png" alt=""><h2>Your cloud backup needs to finish</h2><p>Ignifire found saved cloud data, but no streamable library snapshot. Update the Windows app and run Sync now again.</p><a class="primary-action" data-desktop-download href="${downloadUrl}" style="padding:15px 20px;border-radius:14px;text-decoration:none">Download Ignifire</a></div>`;return`<div class="empty-state"><img src="https://accounts.ignifire.app/ignifire-logo.png" alt=""><h2>Your cloud library is empty</h2><p>Open Ignifire for Windows, sign in, enable Cloud sync, and run Sync now. Your music will appear here after the upload finishes.</p><a class="primary-action" data-desktop-download href="${downloadUrl}" style="padding:15px 20px;border-radius:14px;text-decoration:none">Download Ignifire</a></div>`}
function render(){const main=$('#mainView');$$('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));main.innerHTML=state.view==='albums'?renderAlbums():state.view==='songs'?renderSongs():state.view==='playlists'?renderPlaylists():state.view.startsWith('album:')?renderAlbum(state.view.slice(6)):state.view.startsWith('playlist:')?renderPlaylist(state.view.slice(9)):renderHome();main.focus({preventScroll:true})}

function navigate(view){state.view=view;state.query='';$('#searchInput').value='';render();scrollTo({top:0,behavior:'smooth'})}
function shuffle(items){const result=[...items];for(let index=result.length-1;index>0;index--){const swap=Math.floor(Math.random()*(index+1));[result[index],result[swap]]=[result[swap],result[index]]}return result}
function startQueue(tracks,{shuffleQueue=false,startId=''}={}){const playable=playableTracks(tracks);if(!playable.length){toast('No cloud audio available','Sync these files from the Windows app first.');return}state.queueOriginal=[...playable];state.shuffle=shuffleQueue;state.queue=shuffleQueue?shuffle(playable):[...playable];state.index=Math.max(0,startId?state.queue.findIndex(track=>track.id===startId):0);if(state.index<0)state.index=0;updateModeControls();loadCurrent(true)}
function loadCurrent(autoplay=false){const track=state.queue[state.index];if(!track)return;audio.src=streamURL(track);const album=albumById(track.albumId);$('#nowTitle').textContent=track.title;$('#nowArtist').textContent=`${track.artist} · ${track.album}`;const cover=$('#nowCover');cover.className=`mini-cover ${album?.customCover?'':'cover-fallback'}`;cover.style.backgroundImage=album?.customCover?`url('${album.customCover}')`:'';$('#duration').textContent=track.duration||formatTime(track.durationSeconds);updateMediaSession(track,album);render();if(autoplay)audio.play().catch(()=>toast('Could not start playback','Check your connection and cloud sync status.'))}
function togglePlay(){if(!state.queue.length){startQueue(allTracks(),{shuffleQueue:true});return}audio.paused?audio.play().catch(()=>toast('Could not resume playback')):audio.pause()}
function moveTrack(direction){if(!state.queue.length){startQueue(allTracks(),{shuffleQueue:true});return}if(direction>0&&state.index===state.queue.length-1&&state.repeat==='off'){audio.pause();audio.currentTime=0;return}state.index=(state.index+direction+state.queue.length)%state.queue.length;loadCurrent(true)}
function updateModeControls(){$('#shuffleButton').classList.toggle('active',state.shuffle);$('#shuffleButton').setAttribute('aria-pressed',String(state.shuffle));$('#repeatButton').classList.toggle('active',state.repeat!=='off');$('#repeatButton').dataset.mode=state.repeat;$('#repeatButton').textContent=state.repeat==='one'?'↻¹':'↻';$('#repeatButton').setAttribute('aria-label',state.repeat==='one'?'Repeat one':state.repeat==='all'?'Repeat all':'Repeat off')}
function updateMediaSession(track,album){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:track.artist,album:track.album,artwork:album?.customCover?[{src:album.customCover}]:[]})}catch{}}

document.addEventListener('click',event=>{const view=event.target.closest('[data-view]');if(view){navigate(view.dataset.view);return}const album=event.target.closest('[data-album]');if(album&&!event.target.closest('button')){navigate(`album:${album.dataset.album}`);return}const playlist=event.target.closest('[data-playlist]');if(playlist&&!event.target.closest('button')){navigate(`playlist:${playlist.dataset.playlist}`);return}const playAlbum=event.target.closest('[data-play-album]');if(playAlbum){const item=albumById(playAlbum.dataset.playAlbum);startQueue(item?.tracks||[]);return}const shuffleAlbum=event.target.closest('[data-shuffle-album]');if(shuffleAlbum){const item=albumById(shuffleAlbum.dataset.shuffleAlbum);startQueue(item?.tracks||[],{shuffleQueue:true});return}const playPlaylist=event.target.closest('[data-play-playlist]');if(playPlaylist){startQueue(playlistTracks(findPlaylist(playPlaylist.dataset.playPlaylist)||{}));return}const shufflePlaylist=event.target.closest('[data-shuffle-playlist]');if(shufflePlaylist){startQueue(playlistTracks(findPlaylist(shufflePlaylist.dataset.shufflePlaylist)||{}),{shuffleQueue:true});return}const playTrack=event.target.closest('[data-play-track]');if(playTrack){const track=trackById(playTrack.dataset.playTrack);if(track?.playable)startQueue(allTracks(),{startId:track.id});return}const row=event.target.closest('[data-track]');if(row){const track=trackById(row.dataset.track);if(track?.playable)startQueue(allTracks(),{startId:track.id});return}if(event.target.closest('[data-play-all]'))startQueue(allTracks());if(event.target.closest('[data-shuffle-all]'))startQueue(allTracks(),{shuffleQueue:true})});
$('#searchInput').oninput=event=>{state.query=event.target.value.trim();if(state.view==='home'||state.view.includes(':'))state.view='songs';render()};
$('#playButton').onclick=togglePlay;$('#previousButton').onclick=()=>moveTrack(-1);$('#nextButton').onclick=()=>moveTrack(1);
$('#shuffleButton').onclick=()=>{state.shuffle=!state.shuffle;const current=state.queue[state.index];state.queue=state.shuffle?[current,...shuffle(state.queueOriginal.filter(track=>track.id!==current?.id))]:[...state.queueOriginal];state.index=Math.max(0,state.queue.findIndex(track=>track.id===current?.id));updateModeControls()};
$('#repeatButton').onclick=()=>{state.repeat=state.repeat==='off'?'all':state.repeat==='all'?'one':'off';updateModeControls()};
$('#muteButton').onclick=()=>{audio.muted=!audio.muted;$('#muteButton').textContent=audio.muted?'◗':'◖';$('#muteButton').classList.toggle('active',audio.muted)};
$('#volume').oninput=event=>{audio.volume=Number(event.target.value)/100;audio.muted=false;setRange(event.target,event.target.value)};
$('#progress').oninput=event=>{if(audio.duration)audio.currentTime=audio.duration*Number(event.target.value)/100;setRange(event.target,event.target.value)};
audio.onplay=()=>{$('#playButton').textContent='❚❚';$('#playButton').setAttribute('aria-label','Pause');if('mediaSession'in navigator)navigator.mediaSession.playbackState='playing'};
audio.onpause=()=>{$('#playButton').textContent='▶';$('#playButton').setAttribute('aria-label','Play');if('mediaSession'in navigator)navigator.mediaSession.playbackState=state.queue.length?'paused':'none'};
audio.ontimeupdate=()=>{if(!audio.duration)return;setRange($('#progress'),audio.currentTime/audio.duration*100);$('#elapsed').textContent=formatTime(audio.currentTime);$('#duration').textContent=formatTime(audio.duration)};
audio.onended=()=>state.repeat==='one'?(audio.currentTime=0,audio.play()):moveTrack(1);
audio.onerror=()=>{if(audio.src)toast('This track could not be streamed','Confirm that Cloud sync finished uploading the audio file.')};
if('mediaSession'in navigator){for(const[action,handler]of Object.entries({play:togglePlay,pause:()=>audio.pause(),nexttrack:()=>moveTrack(1),previoustrack:()=>moveTrack(-1)})){try{navigator.mediaSession.setActionHandler(action,handler)}catch{}}}

async function initialize(){setRange($('#volume'),72);applyDownloadUrl(downloadUrl);void resolveDownloadUrl();const signIn=new URL(`${ACCOUNT_ORIGIN}/account`);signIn.searchParams.set('mode','signin');signIn.searchParams.set('return',location.origin);$('#signInLink').href=signIn.href;try{const response=await fetch(`${ACCOUNT_ORIGIN}/v1/web/library`,{credentials:'include',headers:{Accept:'application/json'}});if(response.status===401){$('#authMessage').textContent='Sign in to stream the music saved in your Ignifire cloud library.';$('#authActions').classList.remove('hidden');return}const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Your cloud library could not be loaded.');state.user=payload.user;state.library=payload.library;state.cloud={revision:Number(payload.revision)||0,syncedAt:payload.syncedAt||null,storageUsed:Number(payload.storageUsed)||0};$('#accountChip').textContent=initials(payload.user?.name);$('#accountChip').title=payload.user?.name||'Account settings';$('#authGate').classList.add('hidden');$('#appShell').classList.remove('hidden');render()}catch(error){$('#authMessage').textContent='Ignifire for Web could not reach the account service. Please try again shortly.';$('#authActions').classList.remove('hidden');toast('Web player unavailable',error.message)}}
initialize();
